### PR TITLE
the equals method from TECPublicKeyParameters was not called because …

### PR DESCRIPTION
**Pull request by lgadina**
…it was not declared in the interface

### CODE REVIEW

**Comment by lgadina** [comment]
FreePascal trunk 3.3.1

**Comment by Xor-el** [comment]
@lgadina , first of all, thanks a lot for the pull request.
as regards your error message (**the equals method from TECPublicKeyParameters was not called because it was not declared in the interface**), I don't get such with the latest trunk of today.
can you guide me step by step to reproduce the error?
Thanks.

**Comment by Xor-el** [comment]
@lgadina hopefully fixed those issues with the latest commit.
can you please check? https://github.com/Xor-el/CryptoLib4Pascal/commit/48a77ce40350dfb8aa5255d723b2d5bac5befd33

**Comment by Xor-el** [comment]
please reopen if commit https://github.com/Xor-el/CryptoLib4Pascal/commit/48a77ce40350dfb8aa5255d723b2d5bac5befd33 did not fix your issue.
Thanks.

**Pull request closed without merging**
